# Generated by Django 4.2.7 on 2023-11-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionmodel',
            name='current_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
