# Generated by Django 4.2.7 on 2023-11-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmodel',
            name='current_balance',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='account_num',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='as_of_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='open_balance',
            field=models.BigIntegerField(null=True),
        ),
    ]
