# Generated by Django 4.2.7 on 2023-11-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0002_bankmodel_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmodel',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
